import React, { useEffect, useState } from 'react';
import { adminApi } from '../api';
import { useLang } from '../i18n/LanguageContext';

export default function AdminPage() {
  const { lang , l} = useLang(); const [data, setData] = useState(null); const [catalog, setCatalog] = useState({ syncs: [], reviews: [] }); const [city, setCity] = useState('Singapore'); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [syncing, setSyncing] = useState(false);
  const load = () => { setLoading(true); Promise.all([adminApi.anomalies(), adminApi.catalogSyncs(), adminApi.mappingReviews()]).then(([a, s, r]) => { setData(a.data); setCatalog({ syncs: s.data.syncs, reviews: r.data.reviews }); }).catch(e => setError(e.response?.data?.error || e.message)).finally(() => setLoading(false)); };
  useEffect(load, []);
  const resolve = async (type, id) => { await adminApi.resolveAnomaly(type, id); load(); };
  const sync = async e => { e.preventDefault(); setSyncing(true); setError(''); try { await adminApi.catalogSync({ city }); load(); } catch (e) { setError(e.response?.data?.error || e.message); } finally { setSyncing(false); } };
  const resolveMapping = async (id, status) => { await adminApi.resolveMapping(id, status); load(); };
  if (loading) return <main className="system-page"><p>{l('Loading…', 'Загрузка…')}</p></main>;
  if (error) return <main className="system-page"><p>{error}</p></main>;
  return <main className="admin-page"><h1>{l('Data quality review', 'Контроль качества данных')}</h1><form onSubmit={sync} className="admin-summary"><input value={city} onChange={e => setCity(e.target.value)} placeholder={l('City or IATA code', 'Город или код IATA')} /><button disabled={syncing}>{syncing ? l('Syncing…', 'Синхронизация…') : l('Sync hotel catalog', 'Синхронизировать каталог')}</button></form><div className="admin-summary"><span>{l('Price anomalies', 'Аномалии цен')}: {data.totals.price}</span><span>{l('Score anomalies', 'Аномалии Score')}: {data.totals.score}</span><span>{l('Stale prices', 'Устаревшие цены')}: {data.totals.stale}</span></div>
    <h2>{l('Catalog syncs', 'Синхронизации каталога')}</h2><div className="admin-table">{catalog.syncs.slice(0, 10).map(item => <div className="admin-row" key={item.id}><div><strong>{item.city} ({item.iata_code})</strong><br />{item.status} · {item.processed_count}/{item.total_available ?? '—'} · {new Date(item.started_at).toLocaleString(lang)}</div></div>)}{!catalog.syncs.length && <p>{l('No catalog syncs yet.', 'Синхронизаций каталога пока нет.')}</p>}</div>
    <h2>{l('Hotel mapping review', 'Проверка совпадений отелей')}</h2><div className="admin-table">{catalog.reviews.map(item => <div className="admin-row" key={item.id}><div><strong>{item.imported_name}</strong><br />{l('Candidate', 'Кандидат')}: {item.candidate_name} · {Math.round(item.confidence * 100)}%</div><div><button onClick={() => resolveMapping(item.id, 'approved')}>{l('Approve', 'Одобрить')}</button><button onClick={() => resolveMapping(item.id, 'rejected')}>{l('Reject', 'Отклонить')}</button></div></div>)}{!catalog.reviews.length && <p>{l('No mappings need review.', 'Нет совпадений, требующих проверки.')}</p>}</div>
    <h2>{l('Suspicious prices', 'Подозрительные цены')}</h2><div className="admin-table">{data.price_anomalies.map(item => <div className="admin-row" key={item.id}><div><strong>{item.hotel_name}</strong><br />{item.provider} · {item.anomaly_type} · {item.previous_price ?? '—'} → {item.current_price ?? '—'} {item.currency}</div><button onClick={() => resolve('price', item.id)}>{l('Resolve', 'Закрыть')}</button></div>)}{!data.price_anomalies.length && <p>{l('No open price anomalies.', 'Открытых аномалий цен нет.')}</p>}</div>
    <h2>{l('Score changes', 'Изменения Score')}</h2><div className="admin-table">{data.score_anomalies.map(item => <div className="admin-row" key={item.id}><div><strong>{item.hotel_name}</strong><br />{item.previous_score} → {item.current_score} ({item.delta > 0 ? '+' : ''}{item.delta}) · v{item.score_version}</div><button onClick={() => resolve('score', item.id)}>{l('Resolve', 'Закрыть')}</button></div>)}{!data.score_anomalies.length && <p>{l('No open Score anomalies.', 'Открытых аномалий Score нет.')}</p>}</div>
    <h2>{l('Stale prices', 'Устаревшие цены')}</h2><div className="admin-table">{data.stale_prices.map(item => <div className="admin-row" key={item.price_id}><div><strong>{item.hotel_name}</strong><br />{item.provider} · {item.price_per_night} {item.currency} · {new Date(item.updated_at).toLocaleString(lang)}</div></div>)}{!data.stale_prices.length && <p>{l('No stale prices.', 'Устаревших цен нет.')}</p>}</div>
  </main>;
}
