import React, { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { legalApi } from '../api';
import { useLang } from '../i18n/LanguageContext';

const FALLBACK = {
  terms_version: '1.0', privacy_version: '1.0', effective_date: '2026-07-05',
  operator: { name: '[SERVICE OPERATOR NAME]', registered_address: '[REGISTERED ADDRESS]', registration_number: '[COMPANY / REGISTRATION NUMBER]', jurisdiction: '[JURISDICTION]', contact_email: '[LEGAL CONTACT EMAIL]', privacy_email: '[PRIVACY CONTACT EMAIL]' },
  processors: { email: '[SMTP / EMAIL PROVIDER]', monitoring: 'Sentry (when enabled)', ai: 'OpenRouter (when enabled)', hotels: 'LiteAPI / connected hotel-rate providers', flights: 'Travelpayouts (when enabled)' },
  transfers: { countries: '[DATA HOSTING / PROCESSING COUNTRIES]', safeguard: '[TRANSFER SAFEGUARD]' },
  retention: { account_deletion_days: 30, technical_logs_days: 90, activity_history_months: 24, backup_days: 14 },
};

function Field({ children }) { return <strong className={String(children).startsWith('[') ? 'legal-placeholder' : ''}>{children}</strong>; }
function Section({ title, children }) { return <section><h2>{title}</h2>{children}</section>; }

function Privacy({ c, ru }) {
  const o = c.operator; const p = c.processors;
  return <>
    <Section title={ru ? '1. Кто обрабатывает ваши данные' : '1. Who processes your data'}>
      <p>{ru ? <>Оператором Fairworth является <Field>{o.name}</Field>, регистрационный номер <Field>{o.registration_number}</Field>, адрес: <Field>{o.registered_address}</Field>, юрисдикция: <Field>{o.jurisdiction}</Field>.</> : <>Fairworth is operated by <Field>{o.name}</Field>, registration number <Field>{o.registration_number}</Field>, registered address <Field>{o.registered_address}</Field>, jurisdiction <Field>{o.jurisdiction}</Field>.</>}</p>
      <p>{ru ? <>По вопросам конфиденциальности: <Field>{o.privacy_email}</Field>. Общие юридические вопросы: <Field>{o.contact_email}</Field>.</> : <>Privacy enquiries: <Field>{o.privacy_email}</Field>. General legal enquiries: <Field>{o.contact_email}</Field>.</>}</p>
    </Section>
    <Section title={ru ? '2. Какие данные мы обрабатываем' : '2. Data we process'}>
      <ul><li>{ru ? 'Аккаунт: имя, email, хеш пароля, подтверждение email и настройки безопасности.' : 'Account data: name, email, password hash, email-verification and security settings.'}</li><li>{ru ? 'Профиль и предпочтения: телефон, город, страна, бюджет, предпочтения по отелям и перелётам — только если вы их указали.' : 'Profile and preferences: phone, city, country, budget, hotel and flight preferences when supplied.'}</li><li>{ru ? 'Поиски и поездки: направления, даты, гости, сохранённые варианты, сравнения, наблюдения за ценой и запланированные поездки.' : 'Search and trip data: destinations, dates, guests, saved offers, comparisons, price watches and planned trips.'}</li><li>{ru ? 'Технические данные: IP-адрес, user-agent, идентификаторы сессии, журналы ошибок и безопасности.' : 'Technical data: IP address, user agent, session identifiers, error and security logs.'}</li><li>{ru ? 'Поведенческие события — только после отдельного добровольного согласия.' : 'Behavioural events only after separate optional consent.'}</li><li>{ru ? 'Партнёрские события: переход к поставщику и, если поставщик сообщает, статус бронирования и референс.' : 'Referral events: provider click and, where reported by the provider, booking status and reference.'}</li></ul>
      <p>{ru ? 'Fairworth не собирает платёжные реквизиты: оплата выполняется на сайте внешнего поставщика. Дата рождения не собирается.' : 'Fairworth does not collect payment-card details; payment takes place with the external provider. Date of birth is not collected.'}</p>
    </Section>
    <Section title={ru ? '3. Цели и основания обработки' : '3. Purposes and legal bases'}>
      <ul><li>{ru ? 'Исполнение договора: аккаунт, поиск, сравнение, сохранение поездок, безопасность и поддержка.' : 'Contract performance: account, search, comparison, saved trips, security and support.'}</li><li>{ru ? 'Согласие: поведенческая персонализация и необязательные email-уведомления. Согласие можно отозвать.' : 'Consent: behavioural personalisation and optional email notifications. Consent may be withdrawn.'}</li><li>{ru ? 'Законный интерес: предотвращение мошенничества, защита сервиса, агрегированная оценка качества и диагностика ошибок.' : 'Legitimate interests: fraud prevention, service protection, aggregated quality measurement and error diagnosis.'}</li><li>{ru ? 'Юридическая обязанность: хранение данных, когда этого требует применимое законодательство.' : 'Legal obligations: retention where required by applicable law.'}</li></ul>
    </Section>
    <Section title={ru ? '4. Поставщики и обработчики' : '4. Providers and processors'}>
      <p>{ru ? 'Для работы сервиса могут использоваться следующие категории обработчиков:' : 'The service may use the following categories of processors:'}</p>
      <ul><li>{ru ? <>Email: <Field>{p.email}</Field> — отправка подтверждений, security-писем, уведомлений и дайджестов.</> : <>Email: <Field>{p.email}</Field> for verification, security messages, notifications and digests.</>}</li><li><Field>{p.monitoring}</Field> — {ru ? 'диагностика ошибок и стабильности.' : 'error and reliability monitoring.'}</li><li><Field>{p.ai}</Field> — {ru ? 'необязательное формирование AI-анализа; в запрос передаётся минимально необходимый контекст.' : 'optional AI analysis using the minimum necessary context.'}</li><li><Field>{p.hotels}</Field> — {ru ? 'каталог, наличие и цены отелей.' : 'hotel catalogue, availability and rates.'}</li><li><Field>{p.flights}</Field> — {ru ? 'данные о перелётах и ценах.' : 'flight and fare data.'}</li><li>{ru ? 'Хостинг, база данных и сеть доставки контента — после выбора инфраструктуры их данные должны быть добавлены сюда.' : 'Hosting, database and content-delivery providers must be added here once selected.'}</li></ul>
      <p>{ru ? 'Fairworth не продаёт персональные данные. Поставщики получают только данные, необходимые для соответствующей функции.' : 'Fairworth does not sell personal data. Providers receive only the data required for their function.'}</p>
    </Section>
    <Section title={ru ? '5. Трансграничная передача' : '5. International transfers'}>
      <p>{ru ? <>Данные могут храниться или обрабатываться в следующих странах: <Field>{c.transfers.countries}</Field>. Применяемый механизм защиты передачи: <Field>{c.transfers.safeguard}</Field>. Актуальную информацию можно запросить по адресу конфиденциальности.</> : <>Data may be stored or processed in: <Field>{c.transfers.countries}</Field>. Applicable transfer safeguard: <Field>{c.transfers.safeguard}</Field>. Current details may be requested from the privacy contact.</>}</p>
    </Section>
    <Section title={ru ? '6. Cookies и локальное хранилище' : '6. Cookies and local storage'}>
      <ul><li>{ru ? 'Необходимые cookies: короткая access-сессия, refresh-сессия и CSRF-защита.' : 'Essential cookies: short-lived access session, refresh session and CSRF protection.'}</li><li>{ru ? 'localStorage: язык и минимальная копия состояния авторизованного пользователя.' : 'localStorage: language and a minimal cached authenticated-user state.'}</li><li>{ru ? 'sessionStorage: параметры поиска, корзина поездки и временные development-токены только в локальной разработке.' : 'sessionStorage: search parameters, trip basket and temporary development tokens in local development only.'}</li></ul><p>{ru ? 'Необязательная поведенческая аналитика отключена по умолчанию и включается отдельным переключателем.' : 'Optional behavioural analytics is disabled by default and requires a separate opt-in.'}</p>
    </Section>
    <Section title={ru ? '7. Сроки хранения и удаление' : '7. Retention and deletion'}>
      <ul><li>{ru ? `Аккаунт и предпочтения — пока аккаунт активен; рабочая копия удаляется или обезличивается не позднее ${c.retention.account_deletion_days} дней после подтверждённого удаления, кроме обязательного хранения.` : `Account and preferences are retained while active; the operational copy is deleted or anonymised within ${c.retention.account_deletion_days} days of confirmed deletion except where retention is legally required.`}</li><li>{ru ? 'Сессии и токены — до истечения срока, отзыва или плановой технической очистки.' : 'Sessions and tokens are retained until expiry, revocation or scheduled technical cleanup.'}</li><li>{ru ? `История цен, поисков и поведенческих событий — до ${c.retention.activity_history_months} месяцев, если пользователь не удалит аккаунт раньше.` : `Price, search and behavioural history is retained for up to ${c.retention.activity_history_months} months unless the account is deleted sooner.`}</li><li>{ru ? `Технические и security-журналы — до ${c.retention.technical_logs_days} дней, если инцидент или закон не требует более долгого хранения.` : `Technical and security logs are retained for up to ${c.retention.technical_logs_days} days unless an incident or law requires longer retention.`}</li><li>{ru ? `Резервные копии ротируются в течение ${c.retention.backup_days} дней и не используются для обычной обработки.` : `Backups rotate within ${c.retention.backup_days} days and are not used for ordinary processing.`}</li></ul>
    </Section>
    <Section title={ru ? '8. Ваши права' : '8. Your rights'}>
      <p>{ru ? 'В зависимости от законодательства вы можете запросить доступ, исправление, экспорт, удаление, ограничение или возражение против обработки, а также отозвать согласие и подать жалобу в надзорный орган. Экспорт и удаление доступны в настройках; другие запросы направляйте на адрес конфиденциальности. Перед исполнением запроса может потребоваться подтверждение личности.' : 'Depending on applicable law, you may request access, correction, portability, deletion or restriction, object to processing, withdraw consent and complain to a supervisory authority. Export and deletion are available in settings; other requests should be sent to the privacy contact. Identity verification may be required.'}</p>
    </Section>
    <Section title={ru ? '9. Безопасность и изменения' : '9. Security and changes'}><p>{ru ? 'Применяются разграничение доступа, хеширование паролей, защищённые cookies, CSRF-защита, журналирование и резервное копирование. Абсолютная безопасность передачи и хранения не гарантируется. При существенном изменении политики будет опубликована новая версия и, когда требуется, запрошено новое согласие.' : 'Controls include access restrictions, password hashing, secure cookies, CSRF protection, logging and backups. No transmission or storage method is absolutely secure. Material changes will produce a new published version and, where required, renewed consent.'}</p></Section>
  </>;
}

function Terms({ c, ru }) {
  const o = c.operator;
  return <>
    <Section title={ru ? '1. Стороны и принятие условий' : '1. Parties and acceptance'}><p>{ru ? <>Эти условия регулируют использование Fairworth, предоставляемого <Field>{o.name}</Field>, регистрационный номер <Field>{o.registration_number}</Field>, адрес <Field>{o.registered_address}</Field>. Создавая аккаунт, вы подтверждаете согласие с этой версией Условий и Политикой конфиденциальности.</> : <>These Terms govern Fairworth, provided by <Field>{o.name}</Field>, registration number <Field>{o.registration_number}</Field>, address <Field>{o.registered_address}</Field>. By creating an account, you accept this version of the Terms and the Privacy Policy.</>}</p></Section>
    <Section title={ru ? '2. Что предоставляет Fairworth' : '2. What Fairworth provides'}><p>{ru ? 'Fairworth — информационный сервис сравнения путешествий. Он агрегирует предложения, рассчитывает Fairworth Score, позволяет сравнивать варианты, отслеживать цены и планировать поездки. Fairworth не является отелем, авиакомпанией, туроператором, платёжным агентом или стороной договора бронирования.' : 'Fairworth is a travel-comparison information service. It aggregates offers, calculates the Fairworth Score, supports comparison, price tracking and trip planning. Fairworth is not a hotel, airline, tour operator, payment agent or party to the booking contract.'}</p></Section>
    <Section title={ru ? '3. Аккаунт пользователя' : '3. User account'}><ul><li>{ru ? 'Указывайте точные данные и защищайте пароль и устройства.' : 'Provide accurate information and protect your password and devices.'}</li><li>{ru ? 'Немедленно сообщайте о подозрении на компрометацию аккаунта.' : 'Report suspected account compromise promptly.'}</li><li>{ru ? 'Запрещены автоматизированный сбор данных, обход ограничений, вмешательство в работу сервиса и незаконное использование.' : 'Automated scraping, bypassing controls, service interference and unlawful use are prohibited.'}</li><li>{ru ? 'Оператор может ограничить доступ при нарушении условий, угрозе безопасности или требовании закона.' : 'Access may be restricted for a breach, security risk or legal requirement.'}</li></ul></Section>
    <Section title={ru ? '4. Цены, наличие и Fairworth Score' : '4. Prices, availability and Fairworth Score'}><p>{ru ? 'Цены и наличие поступают от внешних поставщиков, могут быть задержаны, отображаться в другой валюте, не включать налоги, сборы, багаж или дополнительные услуги и измениться до оплаты. Всегда проверяйте итоговую цену, правила отмены, состав тарифа и данные путешественников на сайте поставщика.' : 'Prices and availability come from external providers and may be delayed, use another currency, exclude taxes, fees, baggage or extras, and change before payment. Always verify the final price, cancellation rules, fare inclusions and traveller details with the provider.'}</p><p>{ru ? 'Fairworth Score и AI-анализ являются автоматизированными информационными оценками, а не гарантией качества, экономии, доступности или пригодности варианта.' : 'The Fairworth Score and AI analysis are automated informational assessments, not guarantees of quality, savings, availability or suitability.'}</p></Section>
    <Section title={ru ? '5. Бронирование у внешнего поставщика' : '5. Booking with an external provider'}><p>{ru ? 'При переходе по партнёрской ссылке вы покидаете Fairworth. Бронирование, оплата, возвраты, изменения, поддержка и исполнение поездки регулируются условиями выбранного поставщика. Проверяйте личность поставщика и подтверждение бронирования. Fairworth не хранит данные банковской карты.' : 'A referral link takes you away from Fairworth. Booking, payment, refunds, changes, support and travel fulfilment are governed by the selected provider. Verify the provider and booking confirmation. Fairworth does not store payment-card details.'}</p></Section>
    <Section title={ru ? '6. Партнёрские ссылки и вознаграждение' : '6. Affiliate links and compensation'}><p>{ru ? 'Некоторые ссылки являются партнёрскими. Fairworth может получить комиссию после перехода или завершённого бронирования без отдельной платы с пользователя. Коммерческое вознаграждение не должно изменять формулу Score или скрывать более подходящие результаты; если появятся платные позиции, они должны быть явно помечены.' : 'Some links are affiliate links. Fairworth may receive compensation following a click or completed booking without an additional user charge. Compensation must not alter the Score formula or hide more suitable results; any future sponsored placement must be clearly labelled.'}</p></Section>
    <Section title={ru ? '7. Уведомления' : '7. Notifications'}><p>{ru ? 'Отслеживание цен, напоминания и weekly insights работают на основе доступных данных и не гарантируют обнаружение каждого изменения или своевременную доставку. Настройки можно изменить в аккаунте или по ссылке отписки. Security-сообщения могут отправляться независимо от маркетинговых настроек.' : 'Price watches, reminders and weekly insights rely on available data and do not guarantee detection of every change or timely delivery. Settings may be changed in the account or via an unsubscribe link. Security messages may be sent independently of marketing preferences.'}</p></Section>
    <Section title={ru ? '8. Интеллектуальная собственность' : '8. Intellectual property'}><p>{ru ? 'Код, дизайн, тексты и обозначения Fairworth принадлежат оператору или используются по лицензии. Данные и изображения поставщиков могут принадлежать соответствующим правообладателям. Пользователь получает ограниченное право использовать сервис в личных законных целях.' : 'Fairworth code, design, text and branding belong to the operator or are licensed. Provider data and images may belong to their respective owners. Users receive a limited right to use the service for personal lawful purposes.'}</p></Section>
    <Section title={ru ? '9. Отказ от гарантий и ответственность' : '9. Disclaimers and liability'}><p>{ru ? 'Сервис предоставляется «как есть» и «по мере доступности». В максимально разрешённой законом степени оператор не отвечает за действия поставщиков, отмены, задержки, неверные цены, потерю багажа, визовые требования, форс-мажор или косвенные убытки. Ничто в условиях не исключает ответственность, которую нельзя исключить по закону, и обязательные права потребителя.' : 'The service is provided “as is” and “as available”. To the fullest extent permitted by law, the operator is not liable for provider acts, cancellations, delays, incorrect prices, baggage loss, visa requirements, force majeure or indirect loss. Nothing excludes liability that cannot lawfully be excluded or mandatory consumer rights.'}</p></Section>
    <Section title={ru ? '10. Применимое право, изменения и контакты' : '10. Governing law, changes and contact'}><p>{ru ? <>Применимое право и компетентные суды: <Field>{o.jurisdiction}</Field>, с учётом обязательных прав потребителя по месту проживания. Новая существенная версия публикуется в сервисе и при необходимости требует повторного принятия. Контакт: <Field>{o.contact_email}</Field>.</> : <>Governing law and competent courts: <Field>{o.jurisdiction}</Field>, subject to mandatory rights in the consumer’s country of residence. A material new version will be published and may require renewed acceptance. Contact: <Field>{o.contact_email}</Field>.</>}</p></Section>
  </>;
}

export default function LegalPage() {
  const { type } = useParams(); const { lang } = useLang(); const privacy = type === 'privacy'; const ru = lang === 'ru'; const [config, setConfig] = useState(FALLBACK);
  useEffect(() => { legalApi.current().then(response => setConfig(response.data)).catch(() => {}); }, []);
  const version = privacy ? config.privacy_version : config.terms_version;
  return <main className="legal-page">
    <div className="legal-kicker">Fairworth Legal</div><h1>{privacy ? (ru ? 'Политика конфиденциальности' : 'Privacy Policy') : (ru ? 'Условия использования' : 'Terms of Service')}</h1>
    <div className="legal-meta"><span>{ru ? 'Версия' : 'Version'} {version}</span><span>{ru ? 'Действует с' : 'Effective'} {config.effective_date}</span></div>
    <div className="legal-notice">{ru ? 'Шаблон подготовлен для технической комплектации MVP. Поля, выделенные жёлтым, должны быть заполнены, а документ — проверен юристом в выбранной юрисдикции до публичного запуска.' : 'This template prepares the MVP technically. Yellow fields must be completed and the document reviewed by counsel in the selected jurisdiction before public launch.'}</div>
    {privacy ? <Privacy c={config} ru={ru} /> : <Terms c={config} ru={ru} />}
    <nav className="legal-switch"><Link to={privacy ? '/legal/terms' : '/legal/privacy'}>{privacy ? (ru ? 'Условия использования' : 'Terms of Service') : (ru ? 'Политика конфиденциальности' : 'Privacy Policy')}</Link><Link to="/">{ru ? 'На главную' : 'Home'}</Link></nav>
  </main>;
}
