const HOTEL_CITY_ALIASES = new Map([
  ['сингапур', 'Singapore'],
  ['дубай', 'Dubai'],
  ['абу-даби', 'Abu Dhabi'],
  ['париж', 'Paris'],
  ['parigi', 'Paris'],
  ['parís', 'Paris'],
  ['нью-йорк', 'New York'],
  ['nueva york', 'New York'],
  ['москва', 'Moscow'],
  ['moskau', 'Moscow'],
  ['moscou', 'Moscow'],
  ['mosca', 'Moscow'],
  ['moscú', 'Moscow'],
  ['пекин', 'Beijing'],
  ['peking', 'Beijing'],
  ['pékin', 'Beijing'],
  ['pechino', 'Beijing'],
  ['pekín', 'Beijing'],
  ['шанхай', 'Shanghai'],
  ['shanghái', 'Shanghai'],
  ['нячанг', 'Nha Trang'],
  ['дананг', 'Da Nang'],
  ['куала-лумпур', 'Kuala Lumpur'],
  ['新加坡', 'Singapore'],
  ['迪拜', 'Dubai'],
  ['阿布扎比', 'Abu Dhabi'],
  ['巴黎', 'Paris'],
  ['纽约', 'New York'],
  ['莫斯科', 'Moscow'],
  ['北京', 'Beijing'],
  ['上海', 'Shanghai'],
  ['芽庄', 'Nha Trang'],
  ['岘港', 'Da Nang'],
  ['吉隆坡', 'Kuala Lumpur'],
  ['سنغافورة', 'Singapore'],
  ['دبي', 'Dubai'],
  ['أبوظبي', 'Abu Dhabi'],
  ['باريس', 'Paris'],
  ['نيويورك', 'New York'],
  ['موسكو', 'Moscow'],
  ['بكين', 'Beijing'],
  ['شنغهاي', 'Shanghai'],
  ['نها ترانغ', 'Nha Trang'],
  ['دا نانغ', 'Da Nang'],
  ['كوالالمبور', 'Kuala Lumpur'],
]);

function canonicalHotelCity(value = '') {
  const cleaned = String(value).replace(/\s*\([^)]*\)/, '').trim();
  return HOTEL_CITY_ALIASES.get(cleaned.toLocaleLowerCase()) || cleaned;
}

module.exports = { canonicalHotelCity };
